version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: libweb
      MYSQL_PASSWORD: bucky123@123!
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci", "--log-bin-trust-function-creators=1"]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - libweb_net

  backend:
    build:
      context: ./libweb_Backend
    container_name: backend
    image: libweb_backend:latest
    restart: always
    ports:  
      - "8088:8088"  # 映射后端到宿主机 8088
    networks:
      - libweb_net
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/my_database?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=libweb
      - SPRING_DATASOURCE_PASSWORD=bucky123@123!
      - SERVER_PORT=8088
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m -XX:+UseG1GC
      - TZ=Asia/Shanghai
    volumes:
      - ./settings-docker.xml:/root/.m2/settings.xml

  frontend:
    build:
      context: ./libweb_frontend
    container_name: frontend
    image: libweb_frontend:latest
    restart: always   
    ports:
      - "8087:80"  # 映射前端到宿主机 8087
    networks:
      - libweb_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      # - "443:443" # 添加这一行以开放 443 端口
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - libweb_net
    environment:
      - TZ=Asia/Shanghai

networks:
  libweb_net:
    driver: bridge

volumes:
  db_data:
